const Songs=[{"name":"song1","title":"Manike : thank god | nora fatehi, sidharth malhotra","artist":"jubin & rashmi virag","bimg":"party1.webp"},{"name":"song2","title":"fitoor song | shamshera | ranbir kapoor, vaani kapoor","artist":"arijit & neeti mohan","bimg":"party2.webp"},{"name":"song3","title":"dil ka pata - official music | sita ramam | vishal chandrashekhar","artist":"abhay jodhpurkar","bimg":"party3.webp"},{"name":"song4","title":"isharon isharon mein | twilight mix | jai - parthiv feat.","artist":"abhay & bhavya pandit","bimg":"party4.webp"},{"name":"song5","title":"stay a little longer - full song | half girlfriend | arjun kapoor & shraddha kapoor ","artist":"anushka shahaney","bimg":"party5.webp"},{"name":"song6","title":"tum door mujhse ho kahaan | tum prem ho, lofi","artist":"surya raj kamal","bimg":"party6.webp"},{"name":"song7","title":"lambiyaan si judaiyaan | raabta | sushant rajput & kriti sanon","artist":"arijit singh","bimg":"party7.webp"},{"name":"song8","title":"o khuda | amaal malik - slowed and reverb_","artist":"amaal malik","bimg":"party8.webp"},{"name":"song9","title":"aawara shaam hai | meet bros. ft. piyush mehroliyaa","artist":"shabbir & rits badiani","bimg":"party9.webp"},{"name":"song10","title":"har har sambhu shiv mahadeva | sanand manand vane | abhilipsa panda","artist":"jeetu sharma","bimg":"party10.webp"}];var backimg=document.getElementById("back_img");var img=document.getElementById("img");var title=document.getElementById("song_title");var artist=document.getElementById("song_artist");var song=document.getElementById("audio");var play=document.getElementById("play");var playi=document.getElementById("play_icon");var next=document.getElementById("next");var prev=document.getElementById("prev");var loopsong=document.getElementById("loop_song");var imgBox=document.getElementById("imgBox");var slider=document.getElementById("slider");var vSlider=document.getElementById("vSlider");var vIcon=document.getElementById("vIcon");let loopStatus=!1;window.addEventListener("load",function(){backimg.src="Images/"+Songs[7].bimg;song.src="music/"+Songs[7].name+".mp3";img.src="Images/"+Songs[7].name+".webp";title.textContent=Songs[7].title;artist.textContent=Songs[7].artist;song.volume=0.3;vSlider.value=30;slider.value=0});song.addEventListener("load",function(){slider.value=0});vSlider.addEventListener("input",function(){song.volume=(this.value/100);if(song.volume==0){vIcon.classList.replace("fa-volume-low","fa-volume-xmark")}else{vIcon.classList.replace("fa-volume-xmark","fa-volume-low")}});function loadSongs(Songs){backimg.src="Images/"+Songs.bimg;song.src="music/"+Songs.name+".mp3";img.src="Images/"+Songs.name+".webp";title.textContent=Songs.title;artist.textContent=Songs.artist}
play.addEventListener("click",function(){if(song.paused){imgBox.classList.add("anime1");playi.classList.replace("fa-circle-play","fa-circle-pause");song.play()}else{imgBox.classList.remove("anime1");playi.classList.replace("fa-circle-pause","fa-circle-play");song.pause()}});let songIndex=0;function nextSong(){songIndex=(songIndex+1)%Songs.length;loadSongs(Songs[songIndex]);if(!slider.value){slider.value=0}
if(song.paused){imgBox.classList.add("anime1");playi.classList.replace("fa-circle-play","fa-circle-pause");song.play()}}
function prevSong(){songIndex=(songIndex-1+Songs.length)%Songs.length;loadSongs(Songs[songIndex]);if(!slider.value){slider.value=0}
if(song.paused){imgBox.classList.add("anime1");playi.classList.replace("fa-circle-play","fa-circle-pause");song.play()}}
loopsong.addEventListener("click",function(){this.classList.toggle("active");if(loopStatus===!1){loopStatus=!0;song.loop=!0;console.log("Current song on loop.")}else{loopStatus=!1;song.loop=!1;song.addEventListener("ended",function(){nextSong()});console.log("Current song remove from loop.")}});slider.value=0;song.addEventListener("timeupdate",function(){var getDur=song.duration.toFixed(0);var currentD=song.currentTime.toFixed(0);var sliderVal=(currentD/getDur)*1000;if(getDur){slider.value=sliderVal}
var cTime=document.getElementById("current");var sDuration=document.getElementById("duration");var currDuration=Math.floor(song.currentTime);var duration=Math.floor(song.duration);if(currDuration&&duration){var minTime=Math.floor(currDuration/60);var secTime=(currDuration%60);if(secTime<10){secTime="0"+secTime}
cTime.textContent=minTime+":"+secTime}
if(duration){var min_Time=Math.floor(duration/60);var sec_Time=(duration%60);if(sec_Time<10){sec_Time="0"+sec_Time}
sDuration.textContent=min_Time+":"+sec_Time}});slider.addEventListener("input",function(){song.play();imgBox.classList.add("anime1");playi.classList.replace("fa-circle-play","fa-circle-pause");var getValue=this.value;var maxValue=1000;var songDur=song.duration.toFixed(0);var currentDur=(getValue/maxValue)*songDur;song.currentTime=currentDur});next.addEventListener("click",nextSong);prev.addEventListener("click",prevSong)